/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-08-30 02:40:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>BookClip</title>\r\n");
      out.write("<!--  jquery-->\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<!-- facebook -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/facebookscript.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"../resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!--  Custom Js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"../resources/css/landing-page.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"../resources/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top topnav\"\r\n");
      out.write("\t\trole=\"navigation\">\r\n");
      out.write("\t\t<div class=\"container topnav\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> \r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> \r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> \r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand topnav\" href=\"#\">Start Bootstrap</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#services\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<a name=\"about\"></a>\r\n");
      out.write("\t<div class=\"intro-header\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"intro-message\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Book Clip</h1>\r\n");
      out.write("\t\t\t\t\t\t<h3>보고있는 책을 기록해보세요</h3>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"intro-divider\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\" action=\"/NotFound/index.do\" method=\"post\" name =\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline intro-social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-14\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"userid\" name=\"userid\" class=\"form-control\" placeholder=\"ID\" style=\"min-width: 20em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline intro-social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-14\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"userpd\" name=\"userpd\" class=\"form-control\" placeholder=\"PW\" style=\"min-width: 20em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-inline intro-social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a onclick=\"submit()\" class=\"btn btn-default btn-lg box_size\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-play fa-fw\"></i> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"network-name\">Login</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-default btn-lg box_size\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-cog fa-fw\"></i> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"network-name\">Join</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a onclick=\"checkLoginState();\" class=\"btn btn-default btn-lg box_size\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-facebook fa-fw\"></i> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"network-name\">Facebook</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.intro-header -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Page Content -->\r\n");
      out.write("\r\n");
      out.write("\t<a name=\"services\"></a>\r\n");
      out.write("\t<div class=\"content-section-a\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"section-heading-spacer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading\">\r\n");
      out.write("\t\t\t\t\t\tDeath to the Stock Photo:<br>Special Thanks\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\tA special thanks to <a target=\"_blank\" href=\"http://join.deathtothestockphoto.com/\">Death to the\r\n");
      out.write("\t\t\t\t\t\t\tStock Photo</a> for providing the photographs that you see in this\r\n");
      out.write("\t\t\t\t\t\ttemplate. Visit their website to become a member.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-lg-offset-2 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-responsive\" src=\"img/ipad.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.content-section-a -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content-section-b\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"section-heading-spacer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading\">\r\n");
      out.write("\t\t\t\t\t\t3D Device Mockups<br>by PSDCovers\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\tTurn your 2D designs into high quality, 3D product shots in\r\n");
      out.write("\t\t\t\t\t\tseconds using free Photoshop actions by <a target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://www.psdcovers.com/\">PSDCovers</a>! Visit their\r\n");
      out.write("\t\t\t\t\t\twebsite to download some of their awesome, free photoshop actions!\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-sm-pull-6  col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-responsive\" src=\"img/dog.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.content-section-b -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content-section-a\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<hr class=\"section-heading-spacer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"section-heading\">\r\n");
      out.write("\t\t\t\t\t\tGoogle Web Fonts and<br>Font Awesome Icons\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\tThis template features the 'Lato' font, part of the <a\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\" href=\"http://www.google.com/fonts\">Google Web\r\n");
      out.write("\t\t\t\t\t\t\tFont library</a>, as well as <a target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://fontawesome.io\">icons from Font Awesome</a>.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-5 col-lg-offset-2 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-responsive\" src=\"img/phones.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.content-section-a -->\r\n");
      out.write("\r\n");
      out.write("\t<a name=\"contact\"></a>\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<h2>Connect to Start Bootstrap:</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-inline banner-social-buttons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"https://twitter.com/SBootstrap\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default btn-lg\"><i class=\"fa fa-twitter fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"network-name\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://github.com/IronSummitMedia/startbootstrap\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default btn-lg\"><i class=\"fa fa-github fa-fw\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"network-name\">Github</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"btn btn-default btn-lg\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-linkedin fa-fw\"></i> <span class=\"network-name\">Linkedin</span></a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.banner -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-inline\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"footer-menu-divider\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#about\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"footer-menu-divider\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#services\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"footer-menu-divider\">&sdot;</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright text-muted small\">Copyright &copy; Your\r\n");
      out.write("\t\t\t\t\t\tCompany 2014. All Rights Reserved</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"../resources/js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
