/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-30 15:59:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!--  부트 부분 -->\r\n");
      out.write("<!-- BOOTSTRAP CORE CSS -->\r\n");
      out.write("<link href=\"/NotFound/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- FONT AWESOME ICONS STYLES -->\r\n");
      out.write("<link href=\"/NotFound/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- CUSTOM CSS -->\r\n");
      out.write("<link href=\"/NotFound/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!--  jauery를 사용하기위해선 이걸 작성해줘야함 ..  -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/NotFound/script/facebookscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/NotFound/script/popup.js\"></script>\r\n");
      out.write("<link href=\"/NotFound/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"home\">\r\n");
      out.write("\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Editor</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<div class=\"container topcontainer\">\r\n");
      out.write("\t\t\t\t<div class=\"row scroll-me\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t내 하루를 한 장 한 장 넘기는 순간을 떠올려 보세요. <br>내 이야기를 만질 수 있는 것<br>\r\n");
      out.write("\t\t\t\t\t\t\t내 하루들을 펼쳐보는 일이 가능할지 모르죠. <br>\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#about\" class=\"btn btn-custom btn-two\">Start </a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#clients\" class=\"btn btn-custom btn-one\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"layer_open('layer2');return false;\">Join</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"about\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t<h2 class=\"head-line\">My Editor ?</h2>\r\n");
      out.write("\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t우선은 책을 읽고 후기를 남기는것사이트 입니다.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<div class=\"row text-center\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6 text-center\">\r\n");
      out.write("\t\t\t\t<h2 class=\"head-line\">Start</h2>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal\" action=\"/NotFound/index.do\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">ID</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"userid\" name=\"userid\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" id=\"userpd\" name=\"userpd\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"buttonalign\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"전송\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t\t<fb:login-button = onlogin=\"checkLoginState();\"></fb:login-button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- 여기부터 로그인 부분의 div -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"layer\">\r\n");
      out.write("\t\t<div class=\"bg\"></div>\r\n");
      out.write("\t\t<div id=\"layer2\" class=\"pop-layer\">\r\n");
      out.write("\t\t\t<div class=\"pop-container\">\r\n");
      out.write("\t\t\t\t<div class=\"pop-conts\" style=\"margin-left: 20%; margin-top: 10%\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" name=\"insertUser\" action=\"/NotFound/index.do\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"control-label\" style=\"font-size: 20px\">회원가입</label>\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" id=\"action\" value=\"join\">\r\n");
      out.write("\t\t\t\t\t\t<table name=\"joincss\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"form-group\" style=\"width: 80%; margin-top: 5%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\"><label for=\"control-label\">Name</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td ><input type=\"text\" name=\"joinname\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"form-group\"  style=\"width: 80%; margin-top: 5%; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\"><label for=\"control-label\">아이디</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"joinid\" id=\"joinid\" class=\"form-control\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"idcheck\" class=\"btn btn-info\" onclick=\"checkID(insertUser.joinid.value)\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"form-group\"  style=\"width: 80%; margin-top: 5%; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\"><label for=\"control-label\">비밀번호</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"joinpass\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"form-group\"  style=\"width: 80%; margin-top: 5%; \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<td width=\"100px\" colspan=\"2\"><label for=\"control-label\">확인</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"joinrepass\" onBlur=\"pass_Check()\" class=\"form-control\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"pwdCheck\" id=\"pwdCheck\" size=\"30\" style=\"border-width: 0px\" readonly></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr  style=\"width: 80%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"가입하기\" class=\"btn btn-info\" onclick=\"insert_Clear();\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"취소\" class=\"btn btn-info\" onclick=\"fadelayer();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!--// content-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
